"use strict";

define({
    plaqueMessageSmall: {},
    buttonText: {},
    bonusCardTitle: {
        "fontFamily": "hatten",
        "fontSize": 36,
        "dropShadow": true,
        "dropShadowAngle": 0,
        "dropShadowBlur": 2,
        "dropShadowColor": "#fff77e",
        "dropShadowDistance": 0,
        "fill": ["#b7c0ca", "#ffffff", "#94a3b1", "#ccd2d9", "#ffffff"],
        "fillGradientStops": [0.4, 0.5, 0.5, 0.6],
        "fontWeight": "bold",
        "lineJoin": "round",
        "miterLimit": 18,
        "padding": 10,
        "stroke": "#2b0000",
        "strokeThickness": 5
    },
    winningNumbersTitle: {
        align: "center",
        dropShadow: true,
        dropShadowAngle: 1.3,
        dropShadowBlur: 4,
        dropShadowDistance: 2,
        fill: "#ffff9a",
        fontFamily: "Franklin-Gothic-Condensed",
        fontSize: 26,
        lineJoin: "round",
        padding: 10,
        stroke: "black",
        strokeThickness: 2
    },
    winningNumbersTitleGradient: {
        align: "center",
        dropShadow: true,
        dropShadowAngle: 1.3,
        dropShadowBlur: 4,
        dropShadowDistance: 2,
        dropShadowAlpha: 0,
        fill: ["#ffff9a", "#ffff9a", "#ffbf26"],
        fillGradientStops: [0.2, 0.4, 0.6],
        fontFamily: "Franklin-Gothic-Condensed",
        fontSize: 26,
        lineJoin: "round",
        padding: 10,
        stroke: "black"
    },
    yourNumbers: {
        "dropShadow": true,
        "dropShadowBlur": 2,
        "dropShadowAngle": 2,
        "dropShadowDistance": 0,
        "fill": ["#ffff9a", "#ffbf26"],
        "fillGradientStops": [0.4, 0.8],
        "strokeThickness": 3,
        "fontSize": 26,
        "lineJoin": "round",
        "miterLimit": 28,
        "lineHeight": 30,
        "align": "center",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    wheelBonusInfo: {
        "dropShadow": true,
        "dropShadowAngle": 2,
        "dropShadowBlur": 1,
        "dropShadowColor": "#b32c13",
        "dropShadowDistance": 1,
        "fill": ["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
        "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
        "fontSize": 50,
        "lineJoin": "round",
        "miterLimit": 28,
        "padding": 41,
        "stroke": "#2d0000",
        "strokeThickness": 7,
        "align": "center",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    wheelBonusValues: {
        "dropShadow": true,
        "dropShadowBlur": 2,
        "dropShadowDistance": 0,
        fill: "white",
        "fontSize": 45,
        "fontWeight": "bold",
        "lineJoin": "round",
        "stroke": "#4d2315",
        "strokeThickness": 6,
        "align": "right",
        "fontFamily": "oswald",
        "padding": 4
    },
    wheelBonusValuesGradient: {
        "dropShadow": true,
        "dropShadowBlur": 2,
        "dropShadowDistance": 0,
        "fill": "white",
        "fontSize": 45,
        "fontWeight": "bold",
        "lineJoin": "round",
        "stroke": "#4d2315",
        "strokeThickness": 6,
        "align": "right",
        "fontFamily": "oswald",
        "padding": 4
    },
    wheelBonusMultiplierValues: {
        "dropShadow": true,
        "dropShadowBlur": 15,
        "dropShadowColor": "black",
        "dropShadowDistance": 0,
        "fontSize": 60,
        "fontWeight": "normal",
        "lineJoin": "round",
        "stroke": "#583d24",
        "strokeThickness": 3,
        "fontFamily": "oswald",
        "padding": 10
    },
    wheelBonusMultiplierValuesGradient: {
        "dropShadow": true,
        "dropShadowBlur": 20,
        "dropShadowColor": "#5e3012",
        "dropShadowDistance": 0,
        "fill": ["#fffef1", "#fefc70", "#ffc02f", "#fefc70"],
        "fillGradientStops": [0.3, 0.42, 0.45],
        "fontSize": 60,
        "fontWeight": "normal",
        "lineJoin": "round",
        "stroke": "#583d24",
        "strokeThickness": 5,
        "fontFamily": "oswald",
        "padding": 15
    },
    prizeValueNoWin: {
        "dropShadow": true,
        "dropShadowBlur": 0,
        "dropShadowDistance": 0,
        "fill": ["#f5faf7", "#b9cabe"],
        "strokeThickness": 5,
        "fontSize": 31,
        "lineJoin": "round",
        "padding": 41,
        "miterLimit": 28,
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    prizeValueWin: {
        "dropShadow": true,
        "dropShadowBlur": 0,
        "dropShadowColor": "black",
        "dropShadowDistance": 0,
        "fill": "#ffffff",
        "fontSize": 30,
        "lineJoin": "round",
        "miterLimit": 28,
        "stroke": "black",
        //"#4c1101",
        "strokeThickness": 7,
        "padding": 38,
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    prizeValueWinGradient: {
        "dropShadow": true,
        "dropShadowBlur": 0,
        "dropShadowColor": "black",
        "dropShadowDistance": 0,
        "fill": ["#f8f6f3", "#ffec48"],
        "fontSize": 30,
        "stroke": "black",
        "strokeThickness": 7,
        "padding": 38,
        "miterLimit": 28,
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    //-------------------TEXT SEPARATED INTO UPPER AND LOWER FIELDS FOR iOS ACCENT ISSUE (MISLAND-403)
    winUpToLower: {
        "dropShadow": true,
        "dropShadowBlur": 2,
        "dropShadowAngle": 2,
        "dropShadowDistance": 0,
        "fill": ["#ffff9a", "#ffbf26"],
        "fillGradientStops": [0.4, 0.8],
        "strokeThickness": 3,
        "fontSize": 42,
        "lineJoin": "round",
        "miterLimit": 28,
        "align": "center",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    winUpToUpper: {
        "dropShadow": true,
        "dropShadowBlur": 2,
        "dropShadowAngle": 2,
        "dropShadowDistance": 0,
        "fill": ["#ffff9a", "#ffbf26"],
        "fillGradientStops": [0.4, 0.8],
        "strokeThickness": 3,
        "fontSize": 42,
        "lineJoin": "round",
        "miterLimit": 28,
        "align": "center",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    wheelWinUpToLine1Text: {
        "dropShadow": true,
        "dropShadowBlur": 2,
        "dropShadowAngle": 2,
        "dropShadowDistance": 0,
        "fill": ["#ffff9a", "#ffbf26"],
        "fillGradientStops": [0.4, 0.8],
        "strokeThickness": 3,
        "fontSize": 70,
        "lineJoin": "round",
        "miterLimit": 28,
        "align": "left",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    wheelWinUpToLine1TextPortrait: {
        "dropShadow": true,
        "dropShadowBlur": 2,
        "dropShadowAngle": 2,
        "dropShadowDistance": 0,
        "fill": ["#ffff9a", "#ffbf26"],
        "fillGradientStops": [0.4, 0.8],
        "strokeThickness": 3,
        "fontSize": 70,
        "lineJoin": "round",
        "miterLimit": 28,
        "align": "left",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    wheelWinUpToLine2Text: {
        align: "center",
        dropShadow: true,
        dropShadowAngle: 1.3,
        dropShadowBlur: 4,
        dropShadowDistance: 2,
        fill: "#ffff9a",
        fontFamily: "Franklin-Gothic-Condensed",
        fontSize: 50,
        lineJoin: "round",
        padding: 10,
        stroke: "black",
        strokeThickness: 2
    },
    wheelWinUpToLine2TextGradient: {
        align: "center",
        dropShadow: true,
        dropShadowAngle: 1.3,
        dropShadowBlur: 4,
        dropShadowDistance: 2,
        dropShadowAlpha: 0,
        fill: ["#ffff9a", "#ffff9a", "#ffbf26"],
        fillGradientStops: [0.2, 0.4, 0.6],
        fontFamily: "Franklin-Gothic-Condensed",
        fontSize: 50,
        lineJoin: "round",
        padding: 10,
        stroke: "black"
    },
    wheelWinUpToLine2TextPortrait: {
        "dropShadow": true,
        "dropShadowBlur": 2,
        "dropShadowAngle": 2,
        "dropShadowDistance": 0,
        "fill": ["#ffff9a", "#ffbf26"],
        "fillGradientStops": [0.4, 0.8],
        "strokeThickness": 3,
        "fontSize": 50,
        "lineJoin": "round",
        "miterLimit": 28,
        "align": "left",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    wheelBonusTotalWinLabel: {
        align: "center",
        dropShadow: true,
        dropShadowAngle: 1.3,
        dropShadowBlur: 4,
        dropShadowDistance: 2,
        fill: "white",
        fontFamily: "Franklin-Gothic-Condensed",
        fontSize: 42,
        lineJoin: "round",
        padding: 10,
        stroke: "#5E0000",
        strokeThickness: 2
    },
    wheelBonusTotalWinLabelGradient: {
        align: "center",
        dropShadow: true,
        dropShadowAngle: 1.3,
        dropShadowBlur: 4,
        dropShadowDistance: 2,
        dropShadowAlpha: 0,
        fill: ["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
        fillGradientStops: [0.4, 0.4, 0.5, 0.7],
        fontFamily: "Franklin-Gothic-Condensed",
        fontSize: 42,
        lineJoin: "round",
        padding: 10,
        stroke: "#5E0000"
    },
    wheelWinMultiplierValue: {
        "dropShadow": true,
        "dropShadowAngle": 2,
        "dropShadowBlur": 2,
        "dropShadowColor": "#b32c13",
        "dropShadowDistance": 0,
        "fill": ["#ffffff", "#ffeb45", "#faba3b", "#c3963b", "#faba3b", "#ffeb45", "#ffeb45"],
        "fillGradientStops": [0.33, 0.43, 0.47, 0.55, 0.62, 0.7, 0.82],
        "fontSize": 60,
        "lineJoin": "round",
        "miterLimit": 28,
        "stroke": "#b32c13",
        "strokeThickness": 1,
        "align": "right",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    wheelWinPrizeValue: {
        "dropShadow": true,
        "dropShadowAngle": 2,
        "dropShadowBlur": 2,
        "dropShadowColor": "#b32c13",
        "dropShadowDistance": 0,
        "fill": "#ffffff",
        "fontSize": 60,
        "lineJoin": "round",
        "miterLimit": 28,
        "align": "right",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    wheelWinPrizeValueGradient: {
        "fill": ["#ffffff", "#ffeb45", "#faba3b", "#c3963b", "#faba3b", "#ffeb45", "#ffeb45"],
        "fillGradientStops": [0.33, 0.43, 0.47, 0.55, 0.62, 0.7, 0.82],
        "fontSize": 60,
        "lineJoin": "round",
        "miterLimit": 28,
        "stroke": "#b32c13",
        "strokeThickness": 1,
        "align": "right",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    ticketSelectCostValue: {
        "dropShadow": true,
        "dropShadowAngle": 2,
        "dropShadowBlur": 1,
        "dropShadowColor": "#b32c13",
        "dropShadowDistance": 1,
        "fill": "#FFFFED",
        "fontFamily": "oswald",
        "fontSize": 35,
        "fontWeight": "normal",
        "lineJoin": "round",
        "miterLimit": 14
    },
    bonusWin6: {
        fontFamily: 'oswald',
        fontSize: 92,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableWinColour'
    },
    bonusNoWin6: {
        fontFamily: 'oswald',
        fontSize: 92,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableNoWinColour'
    },
    bonusWin5: {
        fontFamily: 'oswald',
        fontSize: 82,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableWinColour'
    },
    bonusNoWin5: {
        fontFamily: 'oswald',
        fontSize: 82,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableNoWinColour'
    },
    bonusWin4: {
        fontFamily: 'oswald',
        fontSize: 72,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableWinColour'
    },
    bonusNoWin4: {
        fontFamily: 'oswald',
        fontSize: 72,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableNoWinColour'
    },
    bonusWin3: {
        fontFamily: 'oswald',
        fontSize: 62,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableWinColour'
    },
    bonusNoWin3: {
        fontFamily: 'oswald',
        fontSize: 62,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableNoWinColour'
    },
    bonusWin: {
        fontFamily: 'oswald',
        fontSize: 62,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableWinColour'
    },
    bonusNoWin: {
        fontFamily: 'oswald',
        fontSize: 62,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableNoWinColour'
    },
    losePlaqueBodyWithGradient: {
        "dropShadow": true,
        "dropShadowBlur": 4,
        "dropShadowDistance": 0,
        fill: "white",
        stroke: "black",
        "fontSize": 75,
        "miterLimit": 58,
        "lineJoin": "round",
        "padding": 38,
        //"strokeThickness": 5,
        "align": "center",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    losePlaqueBody: {
        "dropShadow": true,
        "dropShadowBlur": 4,
        "dropShadowDistance": 0,
        "dropShadowAlpha": 0,
        "fill": ["white", "#d0d0d0", "#fafafa"],
        "fillGradientStops": [0.5, 0.5, 0.7],
        "fontSize": 75,
        "miterLimit": 58,
        "lineJoin": "round",
        "padding": 38,
        //"strokeThickness": 5,
        stroke: "black",
        "align": "center",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    winPlaqueBodyWithGradient: {
        "dropShadow": true,
        "dropShadowBlur": 4,
        "dropShadowDistance": 1.3,
        fill: "yellow",
        stroke: "black",
        //strokeThickness: 3,
        fontSize: 60,
        lineJoin: "round",
        miterLimit: 58,
        align: "center",
        padding: 38,
        fontFamily: "Franklin-Gothic-Condensed"
    },
    winPlaqueBody: {
        "dropShadow": true,
        "dropShadowBlur": 4,
        "dropShadowAngle": 1.3,
        "dropShadowDistance": 2,
        "dropShadowAlpha": 0,
        "fill": ["#fffff4", "#fffe5a", "#fffff4", "#fffe5a"],
        "fillGradientStops": [0.2, 0.6, 0.8, 1],
        //strokeThickness: 3,
        stroke: "black",
        fontSize: 60,
        lineJoin: "round",
        miterLimit: 58,
        align: "center",
        padding: 38,
        fontFamily: "Franklin-Gothic-Condensed"
    },
    bonusLabel: {
        fontFamily: 'oswald',
        fontSize: 32,
        fontWeight: 'bold',
        fill: 'fontColourBonusCover'
    },
    bonusFind3ToEnd: {
        fontFamily: 'oswald',
        fontSize: 30,
        fontWeight: 'bold',
        fill: 'bonusFind3ToEndTextColour'
    },
    bonusFind3ToWin: {
        fontFamily: 'oswald',
        fontSize: 30,
        fontWeight: 'bold',
        fill: 'bonusFind3ToWinTextColour'
    },
    buyButtonEnabled: {
        "fill": ["#fffff4", "#fffe5a", "#ffc72d", "#fff751"],
        "fillGradientStops": [0.2, 0.5, 0.5, 0.8],
        "lineJoin": "round",
        "stroke": "#1b4d28",
        "strokeThickness": 10,
        "fontSize": 40,
        "miterLimit": 28,
        "align": "left",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    buyButtonDisabled: {
        "fill": ["#fffff4", "#fffe5a", "#ffc72d", "#fff751"],
        "fillGradientStops": [0.2, 0.5, 0.5, 0.8],
        "lineJoin": "round",
        "stroke": "#1b4d28",
        "strokeThickness": 3,
        "fontSize": 40,
        "miterLimit": 28,
        "align": "left",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    buyButtonOver: {
        "fill": ["#fffff4", "#fffe5a", "#ffc72d", "#fff751"],
        "fillGradientStops": [0.2, 0.5, 0.5, 0.8],
        "lineJoin": "round",
        "stroke": "#1b4d28",
        "strokeThickness": 10,
        "fontSize": 40,
        "miterLimit": 28,
        "align": "left",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    buyButtonPressed: {
        "fill": ["#fffff4", "#fffe5a", "#ffc72d", "#fff751"],
        "fillGradientStops": [0.2, 0.5, 0.5, 0.8],
        "lineJoin": "round",
        "stroke": "#1b4d28",
        "strokeThickness": 10,
        "fontSize": 42,
        "miterLimit": 28,
        "align": "left",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    wheelRevealEnabled: {
        align: "center",
        dropShadow: true,
        dropShadowAngle: 1.3,
        dropShadowBlur: 4,
        dropShadowDistance: 2,
        fill: "#ffff9a",
        fontFamily: "Franklin-Gothic-Condensed",
        fontSize: 40,
        lineJoin: "round",
        padding: 10,
        stroke: "#1b4d28",
        strokeThickness: 10
    },
    wheelRevealEnabledGradient: {
        align: "center",
        dropShadow: true,
        dropShadowAngle: 1.3,
        dropShadowBlur: 4,
        dropShadowDistance: 2,
        dropShadowAlpha: 0,
        "fill": ["#fffff4", "#fffe5a", "#ffc72d", "#fff751"],
        "fillGradientStops": [0.2, 0.5, 0.5, 0.8],
        fontFamily: "Franklin-Gothic-Condensed",
        fontSize: 40,
        lineJoin: "round",
        padding: 10,
        stroke: "#1b4d28"
    },
    wheelRevealOver: {
        align: "center",
        dropShadow: true,
        dropShadowAngle: 1.3,
        dropShadowBlur: 4,
        dropShadowDistance: 2,
        fill: "#ffff9a",
        fontFamily: "Franklin-Gothic-Condensed",
        fontSize: 40,
        lineJoin: "round",
        padding: 10,
        stroke: "#1b4d28",
        strokeThickness: 10
    },
    wheelRevealOverGradient: {
        align: "center",
        dropShadow: true,
        dropShadowAngle: 1.3,
        dropShadowBlur: 4,
        dropShadowDistance: 2,
        dropShadowAlpha: 0,
        "fill": ["#fffff4", "#fffe5a", "#ffc72d", "#fff751"],
        "fillGradientStops": [0.2, 0.5, 0.5, 0.8],
        fontFamily: "Franklin-Gothic-Condensed",
        fontSize: 40,
        lineJoin: "round",
        padding: 10,
        stroke: "#1b4d28"
    },
    wheelRevealPressed: {
        align: "center",
        dropShadow: true,
        dropShadowAngle: 1.3,
        dropShadowBlur: 4,
        dropShadowDistance: 2,
        fill: "#ffff9a",
        fontFamily: "Franklin-Gothic-Condensed",
        fontSize: 42,
        lineJoin: "round",
        padding: 10,
        stroke: "#1b4d28",
        strokeThickness: 10
    },
    wheelRevealPressedGradient: {
        align: "center",
        dropShadow: true,
        dropShadowAngle: 1.3,
        dropShadowBlur: 4,
        dropShadowDistance: 2,
        dropShadowAlpha: 0,
        "fill": ["#fffff4", "#fffe5a", "#ffc72d", "#fff751"],
        "fillGradientStops": [0.2, 0.5, 0.5, 0.8],
        fontFamily: "Franklin-Gothic-Condensed",
        fontSize: 42,
        lineJoin: "round",
        padding: 10,
        stroke: "#1b4d28"
    },
    footerLabel: {
        padding: 10,
        fontFamily: 'oswald',
        fill: "#ffec48"
    },
    footerValue: {
        padding: 10,
        fontFamily: 'oswald',
        fill: "#c5c4c2"
    },
    howToPlayTitle: {
        "dropShadow": true,
        "dropShadowAngle": 2,
        "dropShadowBlur": 1,
        "dropShadowColor": "#b32c13",
        "dropShadowDistance": 1,
        "fill": ["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
        "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
        "fontSize": 46,
        "lineJoin": "round",
        "miterLimit": 28,
        "stroke": "#2d0000",
        "strokeThickness": 7,
        "align": "left",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    howToPlayText: {
        "dropShadow": true,
        "dropShadowAngle": 2,
        "dropShadowBlur": 1,
        "dropShadowColor": "black",
        "dropShadowDistance": 2,
        "fontSize": 30,
        "fill": '#dddddd',
        "fontFamily": 'oswald',
        "wordWrap": true,
        "padding": 10
    },
    howToPlayTextCenter: {
        "dropShadow": true,
        "dropShadowAngle": 2,
        "dropShadowBlur": 1,
        "dropShadowColor": "black",
        "dropShadowDistance": 2,
        "fontSize": 30,
        "fill": '#dddddd',
        "fontFamily": 'oswald',
        "align": "center",
        "wordWrap": true,
        "padding": 10
    },
    versionText: {
        fontSize: 18,
        fontFamily: 'oswald',
        fill: '#dddddd',
        padding: 10
    },
    totalWinValue: {
        "dropShadow": true,
        "dropShadowBlur": 2,
        "dropShadowAngle": 2,
        "dropShadowDistance": 0,
        "fill": "#ffffff",
        "fontSize": 120,
        "lineJoin": "round",
        "miterLimit": 28,
        "align": "center",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    totalWinValueGradient: {
        "fill": ["#fffff4", "#fffe5a", "#ffc72d", "#fff751"],
        "fillGradientStops": [0.2, 0.6, 0.6, 0.8],
        "strokeThickness": 3,
        "fontSize": 120,
        "lineJoin": "round",
        "miterLimit": 28,
        "align": "center",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    errorMessage: {
        fontFamily: 'oswald',
        fontSize: 30,
        align: 'center',
        fill: '#eeeeee',
        padding: 10,
        lineHeight: 40
    },
    mainButtonEnabled: {
        "fill": ["#fffff4", "#fffe5a", "#ffc72d", "#fff751"],
        "fillGradientStops": [0.2, 0.5, 0.5, 0.8],
        "lineJoin": "round",
        "stroke": "#1b4d28",
        "strokeThickness": 10,
        "fontSize": 40,
        "miterLimit": 28,
        "align": "left",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    mainButtonDisabled: {
        "fill": ["#fffff4", "#fffe5a", "#ffc72d", "#fff751"],
        "fillGradientStops": [0.2, 0.5, 0.5, 0.8],
        "lineJoin": "round",
        "stroke": "#1b4d28",
        "strokeThickness": 10,
        "fontSize": 40,
        "miterLimit": 28,
        "align": "left",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    mainButtonOver: {
        "fill": ["#fffff4", "#fffe5a", "#ffc72d", "#fff751"],
        "fillGradientStops": [0.2, 0.5, 0.5, 0.8],
        "lineJoin": "round",
        "stroke": "#1b4d28",
        "strokeThickness": 10,
        "fontSize": 40,
        "miterLimit": 28,
        "align": "left",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    mainButtonPressed: {
        "fill": ["#fffff4", "#fffe5a", "#ffc72d", "#fff751"],
        "fillGradientStops": [0.2, 0.5, 0.5, 0.8],
        "lineJoin": "round",
        "stroke": "#1b4d28",
        "strokeThickness": 10,
        "fontSize": 42,
        "miterLimit": 28,
        "align": "left",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    tutorialOKButtonEnabled: {
        "fill": ["#fffff4", "#fffe5a", "#ffc72d", "#fff751"],
        "fillGradientStops": [0.2, 0.5, 0.5, 0.8],
        "lineJoin": "round",
        "stroke": "#1b4d28",
        "strokeThickness": 10,
        "fontSize": 40,
        "miterLimit": 28,
        "align": "left",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    tutorialOKButtonOver: {
        "fill": ["#fffff4", "#fffe5a", "#ffc72d", "#fff751"],
        "fillGradientStops": [0.2, 0.5, 0.5, 0.8],
        "lineJoin": "round",
        "stroke": "#1b4d28",
        "strokeThickness": 10,
        "fontSize": 40,
        "miterLimit": 28,
        "align": "left",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    tutorialOKButtonPressed: {
        "fill": ["#fffff4", "#fffe5a", "#ffc72d", "#fff751"],
        "fillGradientStops": [0.2, 0.5, 0.5, 0.8],
        "lineJoin": "round",
        "stroke": "#1b4d28",
        "strokeThickness": 10,
        "fontSize": 42,
        "miterLimit": 28,
        "align": "left",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    collectBonusInfo: {
        align: "center",
        dropShadow: true,
        dropShadowAngle: 1.3,
        dropShadowBlur: 4,
        dropShadowDistance: 3,
        fill: "#ffff9a",
        fontFamily: "Franklin-Gothic-Condensed",
        fontSize: 45,
        lineJoin: "round",
        padding: 10,
        stroke: "black",
        strokeThickness: 1
    },
    collectBonusInfoGradient: {
        align: "center",
        dropShadow: true,
        dropShadowAngle: 1.3,
        dropShadowBlur: 4,
        dropShadowDistance: 3,
        dropShadowAlpha: 0,
        fill: ["#ffff9a", "#ffff9a", "#ffbf26"],
        fillGradientStops: [0.2, 0.4, 0.6],
        fontFamily: "Franklin-Gothic-Condensed",
        fontSize: 45,
        lineJoin: "round",
        padding: 10,
        stroke: "black"
    },
    collectBonusTotalWin: {
        "dropShadow": true,
        "dropShadowBlur": 2,
        "dropShadowAngle": 2,
        "dropShadowDistance": 0,
        "fill": ["#ffff9a", "#ffbf26"],
        "fillGradientStops": [0.4, 0.8],
        "strokeThickness": 3,
        "fontSize": 40,
        "lineJoin": "round",
        "miterLimit": 28,
        //"lineHeight": 30,
        //"wordWrap": true,
        //"wordWrapWidth": 409,
        "align": "center",
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    collectBonus: {
        "dropShadow": true,
        "dropShadowAngle": 2,
        "dropShadowBlur": 2,
        "dropShadowColor": "#421500",
        "dropShadowDistance": 0,
        "fill": ["#ffffff", "#ffeb45", "#faba3b", "#c3963b", "#faba3b", "#ffeb45", "#ffeb45"],
        "fillGradientStops": [0.33, 0.43, 0.47, 0.55, 0.62, 0.7, 0.82],
        "fontSize": 55,
        "lineJoin": "round",
        "miterLimit": 28,
        "stroke": "#421500",
        "strokeThickness": 3,
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    collectBonusValuePicker: {
        "dropShadow": true,
        "dropShadowAngle": 2,
        "dropShadowBlur": 2,
        "dropShadowColor": "#421500",
        "dropShadowDistance": 0,
        "fill": "#ffffff",
        "fontSize": 55,
        "lineJoin": "round",
        "miterLimit": 28,
        "stroke": "#421500",
        "strokeThickness": 3,
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    collectBonusValuePickerGradient: {
        "fill": ["#ffffff", "#ffeb45", "#faba3b", "#c3963b", "#faba3b", "#ffeb45", "#ffeb45"],
        "fillGradientStops": [0.33, 0.43, 0.47, 0.55, 0.62, 0.7, 0.82],
        "fontSize": 55,
        "lineJoin": "round",
        "miterLimit": 28,
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    errorButtonEnabled: {
        fontFamily: 'oswald',
        fontSize: 38,
        fill: '#ffffff',
        padding: 10
    },
    errorButtonOver: {
        fontFamily: 'oswald',
        fontSize: 38,
        fill: '#ffffff',
        padding: 10
    },
    errorButtonPressed: {
        fontFamily: 'oswald',
        fontSize: 41,
        fill: '#ffffff',
        padding: 10
    },
    bonusCards: {
        "dropShadow": true,
        "dropShadowBlur": 2,
        "dropShadowAngle": 2,
        "dropShadowDistance": 0,
        "fill": ["#ffff9a", "#ffbf26"],
        "fillGradientStops": [0.4, 0.8],
        "strokeThickness": 3,
        "fontSize": 30,
        "lineJoin": "round",
        "miterLimit": 28,
        "lineHeight": 30,
        "align": "center",
        "fontFamily": "Franklin-Gothic-Condensed"
    }
});
//# sourceMappingURL=textStyles.js.map